---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: {{ include "pensieve.fullname" . }}
spec:
  region: {{ .Values.aws_region }}
  backendType: secretsManager
  dataFrom: 
  - /{{ .Values.env }}/{{ include "pensieve.fullname" . }}/env
